### PR TITLE
WIP: Switch to Nuxt & tailwind

### PR DESCRIPTION
**Pull request by Bitti09**
### Warframe Hub Pull Request
---
**Summary (short):**
This PR is mainly for keeping track of the  "Switch to Nuxt(based on Vue) & Tailwindcss" progress

---
**Description:**

Heavy WIP

Notifications & Settings will be added  at the end

---
**Fixes issue (include link):**

---
**Mockups, screenshots, evidence:**

Demo: 
https://warframe-hub.bitti06.now.sh/
---

(Check one)
- [ ] Issue fix
- [ ] Suggestion fulfillment

### CODE REVIEW

**Comment by TobiTenno** [comment]
Just a heads up since it doesn't seem like you restored them: there are success/fail scripts that need to be retained.

**Comment by TobiTenno** [comment]
So as I'm seeing it, you're not working nuxt and tailwind into existing processes, you're rewriting it to be feature-same but with nuxt and tailwind?

**Comment by TobiTenno** [comment]
Also looks like you stripped the necessary bits for running on heroku, please put them back.

**Comment by TobiTenno** [comment]
This is the kind of thing you ask before you decide to move it to a new platform

**Comment by Bitti09** [comment]
Closed until I got more time to work on it

**Pull request closed without merging**
