### PR TITLE
Polish platform picker style

### PR DESCRIPTION
**Pull request by mcoirault**
### Warframe Hub Pull Request
---
---

**Summary (short):**

This PR aims at closing issue #24.

---
**Description:**

The fix adds flex properties to the platform switcher to align its elements.

---
**Fixes issue (include link):**
#24 
---
**Mockups, screenshots, evidence:**
platform-picker

---

(Check one)
- [x] Issue fix
- [ ] Suggestion fulfillment

### CODE REVIEW

**Comment by aliasfalse** [comment]
@mcoirault do you have it deployed somewhere, perchance, for viewing?

**Comment by mcoirault** [comment]
@aliasfalse I don't.

**Comment by MainlandHero** [comment]
@aliasfalse I have reviewed the branch, it looks solid.

@mcoirault, one small that bothers me in the day theme, the color is hard to read when it is on the success, could you change it to the primary color please?

screen shot 2017-10-25 at 12 10 01 pm

**Comment by mcoirault** [comment]
@MainlandHero I made the change to the color. I also made sure it uses white when hovering.

**Comment by aliasfalse** [comment]
@mcoirault sorry if this sound silly, but could you rebase so you pull in the app.json? it allows us to pick up automated deployments of PR's

**Review by EricSihaoLin — APPROVED** [review]
I have manually cloned and checkout branch issue-24, looks solid, no complaints.

**Pull request merged**
