### PR TITLE
Construction

### LINKED ISSUE #308: Add construction progress panel
Summary (short):
---
Give an active panel showing the construction progress for a platform

Description:
---
Get data from `constructionProgress`

Mockups:
---
maybe later

### PR DESCRIPTION
**Pull request by TobiTenno**
**Summary (short):**
Construction!

---
**Description:**
closes #308

### CODE REVIEW

**Comment by TobiTenno** [comment]
this also has a bunch of fixes for some sentry-reported issues

**Comment by EricSihaoLin** [comment]
image
There's something weird when the user first loads in the construction panel causing it to display the incorrect percentages, but upon successive refreshes, the percentages will correct itself.
Not sure if the attached screenshot would tell you of anything.
This behavior is reproducible if you try to load the environment in an incognito tab.

**Comment by TobiTenno** [comment]
capture message is an error with the sentry logger, it probably has the old url and i'd need to update it to a new one for hub pr's....
the active bit is probably from loading an empty worldstate, since that's what first-load pages get, cause they probably don't have any of the bounties.

**Comment by TobiTenno** [comment]
i have a fix for the BountyPanel error in the other PR, i'm looking at what's triggering that capture message error

**Comment by TobiTenno** [comment]
What i'm seeing as to why it's loading like that visually is it's multiplying the value it gets from the worldstate, which is why the unknown is looking fine

**Comment by TobiTenno** [comment]
@EricSihaoLin updated with fixes

**Review by EricSihaoLin — APPROVED** [review]
Not sure if it's a good idea to put Unknown progress out there, even though it is present in the worldstate. I could go either way though.

**Pull request merged**
