### PR TITLE
Checkpoint 1 for Chrome web standards fixes

### PR DESCRIPTION
**Pull request by dsinn**
### Checkpoint 1 for Chrome web standards fixes
---
**Summary (short):**
See #101

---
**Description:**
* Deferred some assets
* Added web manifest
* Added service worker
* Added `alt` to images
* Added `<meta>` tags
* Added `robots.txt`
* Added `rel="noopener"` to external links.
* Made link text more descriptive.

---
**Fixes issue (include link):**
#101 (partially)

---
**Mockups, screenshots, evidence:**
screenshot 2018-08-14 11 20 56

---

(Check one)
- [x] Issue fix
- [ ] Suggestion fulfillment

### CODE REVIEW

**Comment by TobiTenno** [comment]
Wow, that is definitely better.

**Comment by TobiTenno** [comment]
hmmm, i'm getting very different values, but i'm going to run it a few more times

**Comment by TobiTenno** [comment]
oh, it's actually far better from a fully clean run. I think one of my extensions was wonking it up
image

**Comment by dsinn** [comment]
The performance index will probably fluctuate regardless of extensions. 98 though... o_O

**Comment by TobiTenno** [comment]
Could just be from my machine and bandwidth, but yeah, seems pretty good so far

**Review by TobiTenno — APPROVED** [review]

**Comment by dsinn** [comment]
Chrome should throttle the bandwidth by default; if "No throttling" is checked, you should probably change that.

screenshot 2018-08-14 11 54 21

**Comment by TobiTenno** [comment]
image

yeah, closer values, with that

**Pull request merged**
