### PR TITLE
investigate using now for staging apps

### PR DESCRIPTION
**Pull request by TobiTenno**
### Warframe Hub Pull Request
---
**Summary (short):**
giving now a shot

---
**Description:**
:x:

---
**Fixes issue (include link):**
:x:

---
**Mockups, screenshots, evidence:**
testing if this will work for a raw vue project

### CODE REVIEW

**Comment by TobiTenno** [comment]
doesn't seem to be loading fonts

**Comment by Bitti09** [comment]
> doesn't seem to be loading fonts

npw only need the now-start part and the  now.json from my  pr to start nuxt

**Comment by TobiTenno** [comment]
its starting fine, it's not loading the fonts

**Comment by TobiTenno** [comment]
doesn't seem like it'll work with the present route of using the extra server to serve the static content. i'll close this for now.

**Pull request closed without merging**
