### PR TITLE
Event Jumbotron

### PR DESCRIPTION
**Pull request by TobiTenno**
### Warframe Hub Pull Request
---

**Summary (short):** Event support - Jumbotron

---
**Description:** Support for jubotrons

---
**Fixes issue (include link):** #43

---
**Mockups, screenshots, evidence:** see deployment

---

(Check one)
- [ ] Issue fix
- [x] Suggestion fulfillment

### CODE REVIEW

**Review by EricSihaoLin — APPROVED** [review]

**Comment by EricSihaoLin** [comment]
Issue:

- When platform switching from PS4 or XBox, events jumbotron does not show up until a hard page refresh happens.

- When expanding and collapsing the collapsible in the jumbotron, it bounces. This is a result of padding on the panels, since javascript cannot calculate the height of the collapsible when it has padding to predetermine the final location. I suggest removing the paddings on the collapsible and use margins instead.

**Comment by EricSihaoLin** [comment]
image
Possible margin/padding/spacing between the label and the subsections?

**Comment by TobiTenno** [comment]
which label?

**Comment by EricSihaoLin** [comment]
The level label for the events.

**Comment by EricSihaoLin** [comment]
Alright, that's all I had complaints about

**Pull request merged**
