### PR TITLE
Slim up invasions, outpost

### LINKED ISSUE #388: Add a timer to Sentient Outposts
Summary (short):
---
Add a timer to Sentient Outposts to make it easier to tell when it will appear and disappear.

Description:
---
All 'appearance' cycles last for 30 minutes, and all 'disappearance' cycles last the same amount of time as the previous disappearance cycle, plus 3 minutes. When this reaches exactly 3 hours, or more than 3 hours, it loops back to 2 hours. A timer that implements this ruleset would make it much easier to tell when the Sentient Outpost will appear and disappear.

Mockups:
---
I've made an example VB.NET function for the 'disappearance' cycle, which can be found here: https://gist.github.com/Reversance/99d4b49fee98a03f71f8f7f09d82cc45

### PR DESCRIPTION
**Pull request by TobiTenno**
**Summary:**
Slim up the invasions panel with more hovers & less padding
fixes #388 : adds a timer to sentient outpost, no more beta tooltip or no-data section

---
**Mockups, screenshots, evidence:**

Anomalies:
image

Invasions:
image
image

### CODE REVIEW

**Review by EricSihaoLin — APPROVED** [review]

**Comment by taiiat0** [comment]
i'm not sure this style for Invasions is really much better, because of how small the Images have to be scaled to fit within the Margin allotted. 
small enough that it can be difficult to clearly see what it is an Image of.

off the top of my head, perhaps just a single word like 'Strun' or 'Snipetron' or 'Mutagen' plus the Image would be a good middle ground?

**Comment by TobiTenno** [comment]
Single words aren't really filterable because the items aren't all categorized. right now we just remove common appendages to get the image, and that's why the images are both hoverable and tappable, to make it easy to interact and tell what they are.

**Comment by taiiat0** [comment]
hmm, coming from the other angle could be increasing the height of the margin so that the images can be displayed at a more legible scale, hehe.

**Comment by TobiTenno** [comment]
the height of which margin? the image badge/button/thing?

too big and it defeats the point of sticking them in there, cause then i might as well leave them as long strings

**Pull request merged**
