### PR TITLE
feat: move assets from in the bundle to a cdn

### PR DESCRIPTION
**Pull request by TobiTenno**
**Summary:**
Migrate bundled image assets to cdn assets (moving them off of vercel)

I'm gonna look at how we can reduce the size further, but this should at least help

---
**Fixes issue (include link):**
#551 

---
**Mockups, screenshots, evidence:**

Bundle size before:
image

Bundle size after:
image

### CODE REVIEW

**Comment by TobiTenno** [comment]
I've also got incoming changes for the notifications: 
image

**Comment by EricSihaoLin** [comment]
Was this done because the app build/deploy was taking too long? Or does vercel have a strict requirement?

**Comment by TobiTenno** [comment]
> Was this done because the app build/deploy was taking too long? Or does vercel have a strict requirement?

I had to move the team to a pro plan cause it got blocked due to exceeding fair use limits (we used too much bandwidth), so avoid that in the future, moving the asset traffic off of the actual bundle should reduce the traffic by about half.

**Review by EricSihaoLin — APPROVED** [review]

**Pull request merged**
