### PR TITLE
4K Logo, Fix themes and updated loader.svg

### PR DESCRIPTION
**Pull request by nexogone**
### Warframe Hub Pull Request
---
---

**Summary (short):**

- Small changes in the appearance of the loader.
- 4K WFCD Logo (png) + new svg.
- Fix themes + more beautiful code.

---

(Check one)
- [ ] Issue fix
- [x] Suggestion fulfillment

### CODE REVIEW

**Comment by TobiTenno** [comment]
Use an org branch since you've been invited, please, it automatically deploys branches

**Comment by TobiTenno** [comment]
There are a whole bunch of automatically changed css formatting changes, it looks like. In the future, please do a separate commit for those.

**Comment by TobiTenno** [comment]
This is primarily used by the 404 page, please update the path on there so that it picks up the right image. I think it's actually broken right now (no fault of yours)

**Review by TobiTenno — APPROVED** [review]

**Review by EricSihaoLin — APPROVED** [review]

**Pull request merged**
