### PR TITLE
feat: more caching of static content

### PR DESCRIPTION
**Pull request by TobiTenno**
### Warframe Hub Pull Request
---
**Summary (short):**
Adding css to service worker cache

---
**Description:**
Adding css to service worker cache

---
**Fixes issue (include link):**
progress on #101 

---
**Mockups, screenshots, evidence:**
see deployment

---

(Check one)
- [x] Issue fix
- [ ] Suggestion fulfillment

### CODE REVIEW

**Review by dsinn — APPROVED** [review]

**Comment by TobiTenno** [comment]
@dsinn should we add `/map` and the assets for map as well? (and is there any support for wildcards?)

**Comment by dsinn** [comment]
~Adding `/map` and its assets is probably fine~ That page has very many images and I don't know of an easy way to cache all of that, so I'd say save it for later; I just created #165 as a generic ticket for everything related to caching static content, ~so there'd be less work to do later~.  There is no wildcard support, as the browser doesn't have knowledge of the directory structure.  The service worker just requests each item when it runs -- the browser isn't loading the page and then asking the service worker whether or not to cache.

**Comment by TobiTenno** [comment]
cool. it'll take a bit to add it, but it should help, i guess

**Comment by TobiTenno** [comment]
@dsinn anything else you'd prefer removed? I moved most of it back, just added a few routes and the themes to the cache, but not all the assets for those routes

**Comment by dsinn** [comment]
@TobiTenno I don't think `map` would help since we're probably not going to cache all the tiles, but it's not that important and everything else looks good for now.

**Pull request merged**
