### PR TITLE
Glyphs for Fissure Tiers

### PR DESCRIPTION
**Pull request by TobiTenno**
### Warframe Hub Pull Request
---
---

**Summary (short):** glyphs for fissure tiers

---
**Mockups, screenshots, evidence:**
image

---

(Check one)
- [ ] Issue fix
- [x] Suggestion fulfillment

### CODE REVIEW

**Comment by MainlandHero** [comment]
@TobiTenno I get why the glyph is there, but I think it's too small right now imo

**Comment by TobiTenno** [comment]
@MainlandHero what size would you want it?

**Comment by MainlandHero** [comment]
Somewhere in between 15px to 25px, at least decipherable between the different relic ages.

**Comment by MainlandHero** [comment]
I'm okay with this actually. Still on the smaller side, but better than nothing.

**Comment by TobiTenno** [comment]
👍

**Review by EricSihaoLin — APPROVED** [review]

**Pull request merged**
