### PR TITLE
Check for updates for frequently.

### LINKED ISSUE #150: Check for the need to update more frequently
### Check for the need to update more frequently
---

**Summary (short):**
Upon waking up a device, the amount of time you need to wait before the worldstate updates should be reduced.

---
**Description:**
`update` currently has a `setTimeout` value of 30 seconds, but we could check for a timestamp every few seconds instead of only relying on that timeout.

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue
- [x] Suggestion

### PR DESCRIPTION
**Pull request by dsinn**
Closes #150.

### Warframe Hub Pull Request
---
**Summary (short):**
A device that just woke up should get the world state sooner.

---
**Description:**
See issue.

---
**Fixes issue (include link):**
#150 

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue fix
- [x] Suggestion fulfillment

### CODE REVIEW

**Review by TobiTenno — COMMENTED** [review]
As I understand this, which is pretty straightforward, we are updating the timestamp and calling a fetch worldstate every 3 seconds....

This is going to simply eat processing, in my opinion, considering that the worldstate itself doesn't update any more than every 5 minutes, and in the limited case where the processes have been frozen due to the page being open for a long time, we should trigger one of the normal reset cycles by checking _just_ the worldstate timestamp, and if it is out of sync with our current timestamp, then we need to force a full update.

This is fine for a simple timeout update, but why not check if there's actually an update?

**Comment by dsinn** [comment]
Actually, this is only _checking_ the timestamp every three seconds to see if at least 30 seconds have passed since the last worldstate fetch, and only fetching when true.  The frequency of worldstate updates has not changed, besides the edge case where the tab resumes from a sleep that lasted longer than 30 seconds.  The processing required is minuscule (especially compared to timeBadge updates).

**Comment by EricSihaoLin** [comment]
Okay, I see what you're trying to do with the 3 second delay.

My question is which type of user cases are you targeting? Is it just for the people who put our page to sleep? Or is there other user cases that I'm not thinking of?

**Comment by TobiTenno** [comment]
The targeting for it was if the page sleeps, yeah.

**Review by EricSihaoLin — APPROVED** [review]

**Review by TobiTenno — APPROVED** [review]
I think we should also compare to the api timestamp to prevent excess loading of the larger data, but this is fine.

**Comment by dsinn** [comment]
If I understand this correctly, we could just increase `updatePeriod` to 300000.  However, we'd want to define something between 3000ms and 300000ms for how frequently to send a request when the API fails.

**Pull request merged**
