### PR TITLE
feat: Aggregate timer

### LINKED ISSUE #656: :rocket: Refresh button to notify users of new version
### What would you like to see happen?

A notification through the existing notification system or a button when there's a new version of the app to load

An example: https://dev.to/drbragg/handling-service-worker-updates-in-your-vue-pwa-1pip

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #657: :bug: Reset seems to use local time instead of UTC
### Summary

daily reset seems to be using local time instead of UTC time

### Version

hub (Default)

### What browsers are you seeing the problem on?

Brave

### Relevant log output

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by EricSihaoLin**
**Summary:**

Testing Aggregated Timers

---
**Fixes issue (include link):**

No issue fix, new feature
Deprecating redundant and old components

---
**Mockups, screenshots, evidence:**

image

### CODE REVIEW

**Comment by EricSihaoLin** [comment]
Todo:

- [x] Implement colors on font awesome symbols
- [x] Use new pics for steel path and steel essence
- [x] Component hiding via store

**Comment by TobiTenno** [comment]
@EricSihaoLin cool if i help with the TODO's?

**Comment by TobiTenno** [comment]
@EricSihaoLin if you're cool with my changes, I'll merge

**Comment by EricSihaoLin** [comment]
> @EricSihaoLin if you're cool with my changes, I'll merge

This seems good! The icons for different things make the centering looks weird, but that's something we'll have to deal with for now.

**Review by TobiTenno — APPROVED** [review]

**Pull request merged**
