### PR TITLE
Add orb vallis cycle to legacy

### PR DESCRIPTION
**Pull request by EricSihaoLin**
### Warframe Hub Pull Request
---
**Summary (short):**

Due to popular request, adding Orb Vallis cycles to legacy as a stop gap solution.

---
**Description:**

Please see mockup for image.

---
**Fixes issue (include link):**

---
**Mockups, screenshots, evidence:**

screen shot 2018-11-26 at 4 20 38 pm

---

(Check one)
- [ ] Issue fix
- [x] Suggestion fulfillment

### CODE REVIEW

**Comment by TobiTenno** [comment]
looks like you've got some conflicts

**Comment by EricSihaoLin** [comment]
@TobiTenno Please sanity check me, it's been a while since I have worked on either the new or the legacy code.

**Comment by TobiTenno** [comment]
also, news looks.... off

**Review by TobiTenno — CHANGES_REQUESTED** [review]
Not currently runnable on heroku

**Comment by EricSihaoLin** [comment]
This PR is being reworked.

**Pull request closed without merging**
