### PR TITLE
feat: combine how to fish into one guide

### LINKED ISSUE #631: [Feature]: Consolidate How To Fish Pages
### What would you like to see happen?

We should consolidate the 2 fishing pages and use cards where information diverges (ala wiki?)

maybe turn this into the template for a type of blog post format?

Additional bits we need to make sure to mention:
- Using Oxylus will show an indicator on the mini-map in the shape of a goldfhish

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by TobiTenno**
**Summary:**
Make a unified guide for all of the fishing

---
**Fixes issue (include link):**
closes #631 

---
**Mockups, screenshots, evidence:**

### CODE REVIEW

**Comment by EricSihaoLin** [comment]
This looks good, slight suggestion is perhaps make the squares the same size?
image

It's a little bit jarring in the UI perspective if they are different sizes

**Comment by TobiTenno** [comment]
right now i don't do all one size so that it stacks without extra whitespace on mobile. looks like i need to fix exactly how horizontal they are anyway. 
image

**Comment by EricSihaoLin** [comment]
The latest update cleaned it up for mobile, I think this is good enough.
Once all the tests pass after rebase, I can approve

**Review by EricSihaoLin — APPROVED** [review]

**Pull request merged**
