### PR TITLE
Fix Styling for currently selected platform

### PR DESCRIPTION
**Pull request by TobiTenno**
### Warframe Hub Pull Request
---
---

**Summary (short):** Fix for the the currently selected platform looking odd

---
**Description:** Fixes this image

---
**Mockups, screenshots, evidence:** see deployment
 
---

(Check one)
- [x] Issue fix
- [ ] Suggestion fulfillment

### CODE REVIEW

**Comment by EricSihaoLin** [comment]
screen shot 2018-01-18 at 4 35 28 pm

This is the same for Eidolon.

I'm wondering if this should actually be a common or not.

**Comment by TobiTenno** [comment]
i mean, both have black backgrounds, what would we want it to look like otherwise? it's at least distinct, which was my goal... thoughts on alternatives?

**Comment by EricSihaoLin** [comment]
Should we customize that in the styling sheet unique to each theme?

**Comment by TobiTenno** [comment]
Could do.

**Comment by TobiTenno** [comment]
@EricSihaoLin that work for you?

**Review by EricSihaoLin — APPROVED** [review]

**Pull request merged**
