### PR TITLE
fix: remove seconds from end time estimate

### LINKED ISSUE #131: Remove seconds from Invasions ETA
### Warframe Hub Issue
---

**Summary (short):** Because they don't really matter on that anyway

---

**Suggestion**

### PR DESCRIPTION
**Pull request by TobiTenno**
### Warframe Hub Pull Request
---
**Summary (short):** Remove seconds from the invasions Estimation

---
**Description:**

---
**Fixes issue (include link):** closes #131 

---
**Mockups, screenshots, evidence:** See deployment

---

(Check one)
- [x] Issue fix
- [x] Suggestion fulfillment

### CODE REVIEW

**Review by dsinn — COMMENTED** [review]
Could this be a change on the API instead? Looks okay if not.

**Comment by TobiTenno** [comment]
It's a date format on the API, so it definitely could be, but this is something pretty specific to our use-case.

**Review by dsinn — APPROVED** [review]
I can't think of a use case that requires by-the-second invasion ETAs (that are usually off by minutes), but this is probably fine.

**Pull request merged**
