### PR TITLE
Themes

### LINKED ISSUE #212: Theme Support
### Warframe Hub Issue
---

Mostly just need to add the applicable bootswatch themes in less files and get them to be resolved and applied when themes are switched, then add the specific stylings from our old themes.

Largely those that I want to carry over would be:

- [ ] Day
- [x] Night
- [ ] Retro

And add
- [ ] Stalker, like the stalker theme on https://drops.warframestat.us

---

(Check one)
- [x] Issue
- [ ] Suggestion

### PR DESCRIPTION
**Pull request by TobiTenno**
**Summary:**
closes #212 
doesn't add all of the themes or their old styles, but makes it easier to go full-hog with them, since the theme class applies to body instead of just app

oh, and i fully deleted day mode

---
**Fixes issue (include link):** #212 

---
**Mockups, screenshots, evidence:**

see deployment

### CODE REVIEW

**Review by EricSihaoLin — APPROVED** [review]

**Review by EricSihaoLin — COMMENTED** [review]
I have no idea why, but this PR breaks Night Compact @TobiTenno 
You may want to fix before merging.

The problem seems that the span tags are no longer being resolved as valid HTML in the bounty tables.

**Comment by TobiTenno** [comment]
@EricSihaoLin Check it on heroku, not now for that bit. It's been doing that on the now.sh preview for a bit.

**Comment by TobiTenno** [comment]
<details><summary>Basically, to summarize:</summary>

- Night normal on heroku:

 
- Night compact on heroku:


- Night compact on now.sh:


- Fish data on now.sh

</details>

My best guess is something about the current version of bootstrap that we're using is a couple back. i'm planning on doing a separate pr for uplifting stuff related to that so it doesn't break up the rest of development at all, and it's a bit more atomic in changes, since i think there'll need to be a couple other changes (like exactly how we designate slots in the fish pages) and i'll be doing a rewrite for the collapsibles to act more like the compact implementation of bounties, or just find a more compact format that i/we like better

**Comment by EricSihaoLin** [comment]
Okay, gotcha. No problem then, this is good to go.
I will rebase my PR on top of this one.

**Pull request merged**
