### PR TITLE
Add running time to invasions

### LINKED ISSUE #126: Add running time to invasions
### Add running time to invasions
---

**Summary (short):**
Requesting that each invasion has its associated running time displayed next to it.

---
**Description:**
The design is pretty much up in the air:
1. What text to display? For example, Deathsnacks uses %.2f for the value, and the unit is "m" for minutes, "h" for hours or "d" for days depending on how much time has passed.
2. Where to place the text?

(Check one)
- [ ] Issue
- [x] Suggestion

### LINKED ISSUE #132: Make invasion "run time" count up
### Warframe Hub Issue
---

**Summary (short):** Because it's a timer like all the other timers on the page

---
**Description:** Add a section in the update timers function to update that one too

---
**If issue, Reproduction:** Not really an issue of something not working, just something not implemented

---

(Check one)
- [x] Issue
- [ ] Suggestion

### PR DESCRIPTION
**Pull request by dsinn**
### Invasion Running Time
---
**Summary (short):**
Added running time data to each invasion.

---
**Description:**
The existing design doesn't use timeBadges for the ETA, so for consistency I didn't use them for the running time, but I did use popover as suggested on the linked issue. Still very open to suggestions for the UI.

---
**Fixes issue (include link):** Closes #126. Closes #132.

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue fix
- [x] Suggestion fulfillment

### CODE REVIEW

**Comment by TobiTenno** [comment]
looks like it's out of date, @dsinn

**Comment by TobiTenno** [comment]
2 small things:
- [ ] Click should probably be on the progress bar or title, the ETA feels like an odd place
- [ ] The counter should be incremented

**Comment by dsinn** [comment]
@TobiTenno I can do the front-end tweak, but the counter only updates as fast as the countdown (every time `updateInvasions()` runs).  If we do want both the countdown and running time to update every second, then I can do that here even though it's a bit out of scope, but I'd want to apply this to both things, and not just one of them.

**Comment by TobiTenno** [comment]
The countup should be updated with the badges, and the other (the "eta") is calculated by our API, based on the amount of completions. Since that isn't updated but every minute, that part should stay as is.

**Comment by dsinn** [comment]
I've made the changes, but as a user it's quite strange to have a timer that is updated every second juxtaposed against a timer with an identical format that is updated much less frequently. Regardless of whatever technical reason there is behind that, the user is unaware of it.

I'd suggest removing the seconds from the ETA, as those estimates aren't accurate to the second anyway. The lack of precision on the ETA's format is intuitively justified, and wouldn't look like an inconsistency on the event timings.

**Review by TobiTenno — APPROVED** [review]

**Pull request merged**
