### PR TITLE
Add Rivens, style enforcement

### PR DESCRIPTION
**Pull request by TobiTenno**
### Warframe Hub Pull Request
---
**Description:**
Updated dependencies that could be updated passively
Riven display that @Bitti09 had worked on
Styling rules for eslint

---
**Fixes issue (include link):**
:x:

---
**Mockups, screenshots, evidence:**
see deployment

### CODE REVIEW

**Comment by TobiTenno** [comment]
the quote changes are part of the lint changes, they're a bit more adapative now

**Comment by TobiTenno** [comment]
bitti mentioned leaflet's broken, gonna roll that back.

**Comment by TobiTenno** [comment]
leaflet should be fine now, and the files are all the right length and format so prettier doesn't freak out

**Review by EricSihaoLin — DISMISSED** [review]

**Comment by EricSihaoLin** [comment]
Approved, but leaflet seems weird.
When I navigated to https://warframehub-prod-pr-310.herokuapp.com/#/poe/map
The lures and caves do not show up on load, even though they are suppose to. This is fixed by toggling them.

The map label just does not show...

**Comment by EricSihaoLin** [comment]
Leaflet also behaving weirdly on the Orb Vallis map:

image

This happened when I tried to click on one of the K-Drive icons.

Map labels and oddities also broken here...

**Comment by TobiTenno** [comment]
I'll re-test it, i was seeing them last i ran it, but i can drop the versions down again. none of them were breaking version changes, but i guess leaflet might not be following semver

yeah. they're definitely not working on the deploy.

**Comment by TobiTenno** [comment]
hmmm, rolled back the leaflet changes and i'm still not seeing the labels

**Comment by TobiTenno** [comment]
all cleaned up and rebased on the other changes

**Review by EricSihaoLin — APPROVED** [review]

**Pull request merged**
